name: news_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # A powerful http client for Dart -- supports interceptors, FormData, Request Cancellation, File Downloading, etc.
  dio: ^3.0.3

  # Flutter widgets that make it easy to implement the BLoC design pattern
  flutter_bloc: ^3.0.0

  # Package provides internalization and localization facilities, including message translation,
  # plurals and genders, date/number formatting, & parsing and bidirectional text
  intl: ^0.16.0

  # Flutter plugin for launching and URL in the mobile platform
  url_launcher: ^5.2.0

  # Flutter library to load and cache network images
  cached_network_image: ^2.0.0-rc


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^3.2.3

  # Tools to write binaries that run builders
  build_runner: ^1.7.1


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
